language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t brentzey/docker-react .

script:
  - docker run -e CI=true brentzey/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-322886626619"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY